name: cake_it_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  http: ^0.13.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^17.1.0
  equatable: ^2.0.8
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

